In [46]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 200)

print("✓ Required libraries imported and Pandas display settings configured.")

✓ Required libraries imported and Pandas display settings configured.

In [1]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

print("✓ Project directories configured.")

✓ Project directories configured.

In [2]:
csv_files = list(RAW_DIR.glob("*.csv"))

print("✓ Raw CSV dataset search completed.")
print(f"  CSV files found: {len(csv_files)}")

✓ Raw CSV dataset search completed.
  CSV files found: 1

In [4]:
DATA_PATH = csv_files[0]

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (235795, 56)

In [5]:
print("=" * 80)
print("DATASET OVERVIEW")
print("=" * 80)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nColumn names:")
for i, col in enumerate(df.columns):
    print(f"{i:02d}. {col}")

================================================================================
DATASET OVERVIEW
================================================================================
Rows: 235795
Columns: 56

Column names:
00. FILENAME
01. URL
02. URLLength
03. Domain
04. DomainLength
05. IsDomainIP
06. TLD
07. URLSimilarityIndex
08. CharContinuationRate
09. TLDLegitimateProb
10. URLCharProb
11. TLDLength
12. NoOfSubDomain
13. HasObfuscation
14. NoOfObfuscatedChar
15. ObfuscationRatio
16. NoOfLettersInURL
17. LetterRatioInURL
18. NoOfDegitsInURL
19. DegitRatioInURL
20. NoOfEqualsInURL
21. NoOfQMarkInURL
22. NoOfAmpersandInURL
23. NoOfOtherSpecialCharsInURL
24. SpacialCharRatioInURL
25. IsHTTPS
26. LineOfCode
27. LargestLineLength
28. HasTitle
29. Title
30. DomainTitleMatchScore
31. URLTitleMatchScore
32. HasFavicon
33. Robots
34. IsResponsive
35. NoOfURLRedirect
36. NoOfSelfRedirect
37. HasDescription
38. NoOfPopup
39. NoOfiFrame
40. HasExternalFormSubmit
41. HasSocialNet
42. HasSubmitButton
43. HasHiddenFields
44. HasPasswordField
45. Bank
46. Pay
47. Crypto
48. HasCopyrightInfo
49. NoOfImage
50. NoOfCSS
51. NoOfJS
52. NoOfSelfRef
53. NoOfEmptyRef
54. NoOfExternalRef
55. label

In [49]:
print("✓ Displaying the first 5 rows of the dataset.")
df.head()

✓ Displaying the first 5 rows of the dataset.

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,URLCharProb,TLDLength,NoOfSubDomain,HasObfuscation,NoOfObfuscatedChar,ObfuscationRatio,NoOfLettersInURL,LetterRatioInURL,NoOfDegitsInURL,DegitRatioInURL,NoOfEqualsInURL,NoOfQMarkInURL,NoOfAmpersandInURL,NoOfOtherSpecialCharsInURL,SpacialCharRatioInURL,IsHTTPS,LineOfCode,LargestLineLength,HasTitle,Title,DomainTitleMatchScore,URLTitleMatchScore,HasFavicon,Robots,IsResponsive,NoOfURLRedirect,NoOfSelfRedirect,HasDescription,NoOfPopup,NoOfiFrame,HasExternalFormSubmit,HasSocialNet,HasSubmitButton,HasHiddenFields,HasPasswordField,Bank,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,0.061933,3,1,0,0,0.0,18,0.581,0,0.0,0,0,0,1,0.032,1,558,9381,1,à¸‚à¹ˆà¸²à¸§à¸ªà¸” à¸‚à¹ˆà¸²à¸§à¸§à¸±à¸™à¸™à¸µ...,0.000000,0.000000,0,1,1,0,0,0,0,1,0,0,1,1,0,1,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,0.050207,2,1,0,0,0.0,9,0.391,0,0.0,0,0,0,2,0.087,1,618,9381,1,johannes gutenberg-universitÃ¤t mainz,55.555556,55.555556,1,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,0.064129,2,2,0,0,0.0,15,0.517,0,0.0,0,0,0,2,0.069,1,467,682,1,voice fm southampton,46.666667,46.666667,0,1,1,0,0,1,0,0,0,0,1,1,0,0,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,0.057606,3,1,0,0,0.0,13,0.500,0,0.0,0,0,0,1,0.038,1,6356,26824,1,home page: seminars in fetal and neonatal medi...,0.000000,0.000000,0,1,1,0,0,0,1,12,0,1,1,1,0,0,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,0.059441,3,1,0,0,0.0,20,0.606,0,0.0,0,0,0,1,0.030,1,6089,28404,1,fundaciÃ³n rewilding argentina,100.000000,100.000000,0,1,1,1,1,1,0,2,0,1,1,1,0,1,1,0,1,244,15,34,72,1,85,1

In [50]:
print("✓ Inspecting dataset structure, column names, data types, and memory usage.")
df.info()

✓ Inspecting dataset structure, column names, data types, and memory usage.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235795 entries, 0 to 235794
Data columns (total 56 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   FILENAME                    235795 non-null  object
 1   URL                         235795 non-null  object
 2   URLLength                   235795 non-null  int64
 3   Domain                      235795 non-null  object
 4   DomainLength                235795 non-null  int64
 5   IsDomainIP                  235795 non-null  int64
 6   TLD                         235795 non-null  object
 7   URLSimilarityIndex          235795 non-null  float64
 8   CharContinuationRate        235795 non-null  float64
 9   TLDLegitimateProb           235795 non-null  float64
 10  URLCharProb                 235795 non-null  float64
 11  TLDLength                   235795 non-null  int64
 12  NoOfSubDomain               235795 non-null  int64
 13  HasObfuscation              235795 non-null  int64
 14  NoOfObfuscatedChar          235795 non-null  int64
 15  ObfuscationRatio            235795 non-null  float64
 16  NoOfLettersInURL            235795 non-null  int64
 17  LetterRatioInURL            235795 non-null  float64
 18  NoOfDegitsInURL             235795 non-null  int64
 19  DegitRatioInURL             235795 non-null  float64
 20  NoOfEqualsInURL             235795 non-null  int64
 21  NoOfQMarkInURL              235795 non-null  int64
 22  NoOfAmpersandInURL          235795 non-null  int64
 23  NoOfOtherSpecialCharsInURL  235795 non-null  int64
 24  SpacialCharRatioInURL       235795 non-null  float64
 25  IsHTTPS                     235795 non-null  int64
 26  LineOfCode                  235795 non-null  int64
 27  LargestLineLength           235795 non-null  int64
 28  HasTitle                    235795 non-null  int64
 29  Title                       235795 non-null  object
 30  DomainTitleMatchScore       235795 non-null  float64
 31  URLTitleMatchScore          235795 non-null  float64
 32  HasFavicon                  235795 non-null  int64
 33  Robots                      235795 non-null  int64
 34  IsResponsive                235795 non-null  int64
 35  NoOfURLRedirect             235795 non-null  int64
 36  NoOfSelfRedirect            235795 non-null  int64
 37  HasDescription              235795 non-null  int64
 38  NoOfPopup                   235795 non-null  int64
 39  NoOfiFrame                  235795 non-null  int64
 40  HasExternalFormSubmit       235795 non-null  int64
 41  HasSocialNet                235795 non-null  int64
 42  HasSubmitButton             235795 non-null  int64
 43  HasHiddenFields             235795 non-null  int64
 44  HasPasswordField            235795 non-null  int64
 45  Bank                        235795 non-null  int64
 46  Pay                         235795 non-null  int64
 47  Crypto                      235795 non-null  int64
 48  HasCopyrightInfo            235795 non-null  int64
 49  NoOfImage                   235795 non-null  int64
 50  NoOfCSS                     235795 non-null  int64
 51  NoOfJS                      235795 non-null  int64
 52  NoOfSelfRef                 235795 non-null  int64
 53  NoOfEmptyRef                235795 non-null  int64
 54  NoOfExternalRef             235795 non-null  int64
 55  label                       235795 non-null  int64
dtypes: float64(10), int64(41), object(5)
memory usage: 100.7+ MB

In [51]:
print("✓ Generating descriptive statistics for all dataset features.")
df.describe(include="all").T

✓ Generating descriptive statistics for all dataset features.

                               count  unique                                    top    freq          mean            std       min        25%       50%       75%         max
FILENAME                      235795  235795                             521848.txt       1           NaN            NaN       NaN        NaN       NaN       NaN         NaN
URL                           235795  235370  https://disclosepack.myportfolio.com/       2           NaN            NaN       NaN        NaN       NaN       NaN         NaN
URLLength                   235795.0     NaN                                    NaN     NaN     34.573095      41.314153      13.0       23.0      27.0      34.0      6097.0
Domain                        235795  220086                                ipfs.io    1197           NaN            NaN       NaN        NaN       NaN       NaN         NaN
DomainLength                235795.0     NaN                                    NaN     NaN     21.470396       9.150793       4.0       16.0      20.0      24.0       110.0
IsDomainIP                  235795.0     NaN                                    NaN     NaN      0.002706       0.051946       0.0        0.0       0.0       0.0         1.0
TLD                           235795     695                                    com  112554           NaN            NaN       NaN        NaN       NaN       NaN         NaN
URLSimilarityIndex          235795.0     NaN                                    NaN     NaN     78.430778      28.976055  0.155574  57.024793     100.0     100.0       100.0
CharContinuationRate        235795.0     NaN                                    NaN     NaN      0.845508       0.216632       0.0       0.68       1.0       1.0         1.0
TLDLegitimateProb           235795.0     NaN                                    NaN     NaN      0.260423       0.251628       0.0   0.005977  0.079963  0.522907    0.522907
URLCharProb                 235795.0     NaN                                    NaN     NaN      0.055747       0.010587  0.001083   0.050747   0.05797  0.062875    0.090824
TLDLength                   235795.0     NaN                                    NaN     NaN      2.764456       0.599739       2.0        2.0       3.0       3.0        13.0
NoOfSubDomain               235795.0     NaN                                    NaN     NaN      1.164758       0.600969       0.0        1.0       1.0       1.0        10.0
HasObfuscation              235795.0     NaN                                    NaN     NaN      0.002057       0.045306       0.0        0.0       0.0       0.0         1.0
NoOfObfuscatedChar          235795.0     NaN                                    NaN     NaN      0.024861       1.876249       0.0        0.0       0.0       0.0       447.0
ObfuscationRatio            235795.0     NaN                                    NaN     NaN      0.000138       0.003817       0.0        0.0       0.0       0.0       0.348
NoOfLettersInURL            235795.0     NaN                                    NaN     NaN     19.428919       29.09033       0.0       10.0      14.0      20.0      5191.0
LetterRatioInURL            235795.0     NaN                                    NaN     NaN      0.515946       0.123315       0.0      0.435     0.519     0.594       0.926
NoOfDegitsInURL             235795.0     NaN                                    NaN     NaN      1.881011      11.886695       0.0        0.0       0.0       0.0      2011.0
DegitRatioInURL             235795.0     NaN                                    NaN     NaN      0.028616       0.070897       0.0        0.0       0.0       0.0       0.684
NoOfEqualsInURL             235795.0     NaN                                    NaN     NaN      0.062241       0.934704       0.0        0.0       0.0       0.0       176.0
NoOfQMarkInURL              235795.0     NaN                                    NaN     NaN      0.029403       0.193505       0.0        0.0       0.0       0.0         4.0
NoOfAmpersandInURL          235795.0     NaN                                    NaN     NaN      0.025056       0.836448       0.0        0.0       0.0       0.0       149.0
NoOfOtherSpecialCharsInURL  235795.0     NaN                                    NaN     NaN      2.340198       3.527603       0.0        1.0       1.0       3.0       499.0
SpacialCharRatioInURL       235795.0     NaN                                    NaN     NaN      0.063309       0.032393       0.0      0.038      0.05     0.083       0.397
IsHTTPS                     235795.0     NaN                                    NaN     NaN      0.782625       0.412461       0.0        1.0       1.0       1.0         1.0
LineOfCode                  235795.0     NaN                                    NaN     NaN   1141.900443    3419.950513       2.0       18.0     429.0    1277.0    442666.0
LargestLineLength           235795.0     NaN                                    NaN     NaN  12789.532624  152201.099228      22.0      200.0    1090.0    8047.0  13975732.0
HasTitle                    235795.0     NaN                                    NaN     NaN      0.861261       0.345675       0.0        1.0       1.0       1.0         1.0
Title                         235795  197874                                      0   32719           NaN            NaN       NaN        NaN       NaN       NaN         NaN
DomainTitleMatchScore       235795.0     NaN                                    NaN     NaN     50.131427      49.676981       0.0        0.0      75.0     100.0       100.0
URLTitleMatchScore          235795.0     NaN                                    NaN     NaN     52.122098      49.600564       0.0        0.0     100.0     100.0       100.0
HasFavicon                  235795.0     NaN                                    NaN     NaN      0.361768       0.480513       0.0        0.0       0.0       1.0         1.0
Robots                      235795.0     NaN                                    NaN     NaN      0.266541       0.442151       0.0        0.0       0.0       1.0         1.0
IsResponsive                235795.0     NaN                                    NaN     NaN      0.624513       0.484249       0.0        0.0       1.0       1.0         1.0
NoOfURLRedirect             235795.0     NaN                                    NaN     NaN      0.133438       0.340048       0.0        0.0       0.0       0.0         1.0
NoOfSelfRedirect            235795.0     NaN                                    NaN     NaN      0.040107        0.19621       0.0        0.0       0.0       0.0         1.0
HasDescription              235795.0     NaN                                    NaN     NaN      0.440183        0.49641       0.0        0.0       0.0       1.0         1.0
NoOfPopup                   235795.0     NaN                                    NaN     NaN      0.221765        3.87054       0.0        0.0       0.0       0.0       602.0
NoOfiFrame                  235795.0     NaN                                    NaN     NaN      1.588638       5.762561       0.0        0.0       0.0       1.0      1602.0
HasExternalFormSubmit       235795.0     NaN                                    NaN     NaN      0.043987       0.205067       0.0        0.0       0.0       0.0         1.0
HasSocialNet                235795.0     NaN                                    NaN     NaN       0.45657       0.498111       0.0        0.0       0.0       1.0         1.0
HasSubmitButton             235795.0     NaN                                    NaN     NaN      0.414301       0.492602       0.0        0.0       0.0       1.0         1.0
HasHiddenFields             235795.0     NaN                                    NaN     NaN      0.377799       0.484838       0.0        0.0       0.0       1.0         1.0
HasPasswordField            235795.0     NaN                                    NaN     NaN      0.102263       0.302994       0.0        0.0       0.0       0.0         1.0
Bank                        235795.0     NaN                                    NaN     NaN      0.127089       0.333074       0.0        0.0       0.0       0.0         1.0
Pay                         235795.0     NaN                                    NaN     NaN      0.237007       0.425247       0.0        0.0       0.0       0.0         1.0
Crypto                      235795.0     NaN                                    NaN     NaN      0.023474       0.151403       0.0        0.0       0.0       0.0         1.0
HasCopyrightInfo            235795.0     NaN                                    NaN     NaN      0.486775       0.499826       0.0        0.0       0.0       1.0         1.0
NoOfImage                   235795.0     NaN                                    NaN     NaN     26.075689      79.411815       0.0        0.0       8.0      29.0      8956.0
NoOfCSS                     235795.0     NaN                                    NaN     NaN      6.333111      74.866296       0.0        0.0       2.0       8.0     35820.0
NoOfJS                      235795.0     NaN                                    NaN     NaN     10.522305      22.312192       0.0        0.0       6.0      15.0      6957.0
NoOfSelfRef                 235795.0     NaN                                    NaN     NaN     65.071113     176.687539       0.0        0.0      12.0      88.0     27397.0
NoOfEmptyRef                235795.0     NaN                                    NaN     NaN      2.377629      17.641097       0.0        0.0       0.0       1.0      4887.0
NoOfExternalRef             235795.0     NaN                                    NaN     NaN     49.262516      161.02743       0.0        1.0      10.0      57.0     27516.0
label                       235795.0     NaN                                    NaN     NaN      0.571895       0.494805       0.0        0.0       1.0       1.0         1.0

In [52]:
duplicate_rows = df.duplicated().sum()

print("✓ Duplicate row check completed.")
print("Duplicate rows:", duplicate_rows)
print(
    "Duplicate percentage:",
    round(duplicate_rows / len(df) * 100, 4),
    "%"
)

✓ Duplicate row check completed.
Duplicate rows: 0
Duplicate percentage: 0.0 %

In [53]:
print("✓ Searching for URL-related columns in the dataset.")

url_columns = [col for col in df.columns if "url" in col.lower()]

print("URL-related columns found:")
for col in url_columns:
    print(f"  - {col}")

✓ Searching for URL-related columns in the dataset.
URL-related columns found:
  - URL
  - URLLength
  - URLSimilarityIndex
  - URLCharProb
  - NoOfLettersInURL
  - LetterRatioInURL
  - NoOfDegitsInURL
  - DegitRatioInURL
  - NoOfEqualsInURL
  - NoOfQMarkInURL
  - NoOfAmpersandInURL
  - NoOfOtherSpecialCharsInURL
  - SpacialCharRatioInURL
  - URLTitleMatchScore
  - NoOfURLRedirect

In [54]:
columns_to_check = [
    'URL',
    'URLLength',
    'URLSimilarityIndex',
    'URLCharProb',
    'NoOfLettersInURL',
    'LetterRatioInURL',
    'NoOfDegitsInURL',
    'DegitRatioInURL',
    'NoOfEqualsInURL',
    'NoOfQMarkInURL',
    'NoOfAmpersandInURL',
    'NoOfOtherSpecialCharsInURL',
    'SpacialCharRatioInURL',
    'URLTitleMatchScore',
    'NoOfURLRedirect'
]

print("✓ Checking duplicate values across selected URL-related features.\n")

for col in columns_to_check:
    duplicates = df[col].duplicated().sum()
    percentage = round(duplicates / len(df) * 100, 4)

    print(f"Column: {col}")
    print(f"Duplicate count: {duplicates}")
    print(f"Duplicate percentage: {percentage}%\n")

✓ Checking duplicate values across selected URL-related features.

Column: URL
Duplicate count: 425
Duplicate percentage: 0.1802%

Column: URLLength
Duplicate count: 235313
Duplicate percentage: 99.7956%

Column: URLSimilarityIndex
Duplicate count: 199435
Duplicate percentage: 84.5798%

Column: URLCharProb
Duplicate count: 8374
Duplicate percentage: 3.5514%

Column: NoOfLettersInURL
Duplicate count: 235374
Duplicate percentage: 99.8215%

Column: LetterRatioInURL
Duplicate count: 235086
Duplicate percentage: 99.6993%

Column: NoOfDegitsInURL
Duplicate count: 235613
Duplicate percentage: 99.9228%

Column: DegitRatioInURL
Duplicate count: 235220
Duplicate percentage: 99.7561%

Column: NoOfEqualsInURL
Duplicate count: 235770
Duplicate percentage: 99.9894%

Column: NoOfQMarkInURL
Duplicate count: 235790
Duplicate percentage: 99.9979%

Column: NoOfAmpersandInURL
Duplicate count: 235764
Duplicate percentage: 99.9869%

Column: NoOfOtherSpecialCharsInURL
Duplicate count: 235721
Duplicate percentage: 99.9686%

Column: SpacialCharRatioInURL
Duplicate count: 235555
Duplicate percentage: 99.8982%

Column: URLTitleMatchScore
Duplicate count: 235298
Duplicate percentage: 99.7892%

Column: NoOfURLRedirect
Duplicate count: 235793
Duplicate percentage: 99.9992%

In [55]:
columns_to_check = [
    'URL',
    'URLLength',
    'URLSimilarityIndex',
    'URLCharProb',
    'NoOfLettersInURL',
    'LetterRatioInURL',
    'NoOfDegitsInURL',
    'DegitRatioInURL',
    'NoOfEqualsInURL',
    'NoOfQMarkInURL',
    'NoOfAmpersandInURL',
    'NoOfOtherSpecialCharsInURL',
    'SpacialCharRatioInURL',
    'URLTitleMatchScore',
    'NoOfURLRedirect'
]

print("✓ Inspecting examples of duplicate values in selected URL-related features.")

for col in columns_to_check:
    duplicate_rows = df[df[col].duplicated(keep=False)].sort_values(col)

    print(f"\nColumn: {col}")
    print(duplicate_rows.head(20))

✓ Inspecting examples of duplicate values in selected URL-related features.

Column: URL
            FILENAME                                                URL  URLLength                                             Domain  DomainLength  IsDomainIP   TLD  URLSimilarityIndex  \
219489  oph11312.txt              http://2f3a.reicrut-chat.workers.dev/         37                      2f3a.reicrut-chat.workers.dev            29           0   dev           27.903290
57609   oph00115.txt              http://2f3a.reicrut-chat.workers.dev/         36                      2f3a.reicrut-chat.workers.dev            29           0   dev           27.903290
227564   7729466.txt                             http://34.149.138.117/         21                                     34.149.138.117            14           1   117           38.231293
27166   oph04235.txt                             http://34.149.138.117/         22                                     34.149.138.117            14           1   117           38.231293
147448   7990740.txt  http://595221.selcdn.ru/qwerty-ohdhdjejnnad-na...         62                                   595221.selcdn.ru            16           0    ru           27.442490
189978  oph09785.txt  http://595221.selcdn.ru/qwerty-ohdhdjejnnad-na...         63                                   595221.selcdn.ru            16           0    ru           27.442490
57315   oph14785.txt  http://595221.selcdn.ru/qwerty-ohdhdjejnnad-na...         63                                   595221.selcdn.ru            16           0    ru           27.442490
31955    7990736.txt  http://595221.selcdn.ru/qwerty-ohdhdjejnnad-na...         62                                   595221.selcdn.ru            16           0    ru           27.442490
197956   8020396.txt               http://91.239.125.28/postchs/sms.php         35                                      91.239.125.28            13           1    28           24.188408
126246  oph00584.txt               http://91.239.125.28/postchs/sms.php         36                                      91.239.125.28            13           1    28           24.188408
128125   8029477.txt  http://akareal.com.vn/wp-admin/js/hku/sa/netfl...         74                                     akareal.com.vn            14           0    vn           15.029337
161155  oph02644.txt  http://akareal.com.vn/wp-admin/js/hku/sa/netfl...         75                                     akareal.com.vn            14           0    vn           15.029337
18133    8034372.txt  http://app-batasotak1244acces.kvoiffugw9-yk26e...         89  app-batasotak1244acces.kvoiffugw9-yk26ed5vg379...            63           0  link           11.179519
216082  oph03976.txt  http://app-batasotak1244acces.kvoiffugw9-yk26e...         90  app-batasotak1244acces.kvoiffugw9-yk26ed5vg379...            63           0  link           11.043140
219064  oph03829.txt  http://app-inf0.tacbxjsspw-ypj68pkov3l2.p.temp...         57  app-inf0.tacbxjsspw-ypj68pkov3l2.p.temp-site.link            49           0  link           22.652228
194438   8034577.txt  http://app-inf0.tacbxjsspw-ypj68pkov3l2.p.temp...         56  app-inf0.tacbxjsspw-ypj68pkov3l2.p.temp-site.link            49           0  link           22.652228
91011    8034377.txt  http://app-mumerlah589ieks.kvoiffugw9-yk26ed5v...         86  app-mumerlah589ieks.kvoiffugw9-yk26ed5vg379.p....            60           0  link           12.803237
20453   oph03973.txt  http://app-mumerlah589ieks.kvoiffugw9-yk26ed5v...         87  app-mumerlah589ieks.kvoiffugw9-yk26ed5vg379.p....            60           0  link           12.643519
222957   8013789.txt    http://app.it.185-174-136-148.cprapid.com/bper/         46                 app.it.185-174-136-148.cprapid.com            34           0   com           25.667324
224102     op456.txt    http://app.it.185-174-136-148.cprapid.com/bper/         47                 app.it.185-174-136-148.cprapid.com            34           0   com           25.667324

        CharContinuationRate  TLDLegitimateProb  URLCharProb  TLDLength  NoOfSubDomain  HasObfuscation  NoOfObfuscatedChar  ObfuscationRatio  NoOfLettersInURL  LetterRatioInURL  NoOfDegitsInURL  \
219489              0.360000           0.000961     0.051950          3              2               0                   0               0.0                23             0.622                2
57609               0.360000           0.000961     0.051950          3              2               0                   0               0.0                23             0.639                2
227564              0.400000           0.000000     0.001404          3              2               0                   0               0.0                 0             0.000               11
27166               0.400000           0.000000     0.001404          3              2               0                   0               0.0                 0             0.000               11
147448              1.000000           0.018013     0.039487          2              1               0                   0               0.0                41             0.661                7
189978              1.000000           0.018013     0.039556          2              1               0                   0               0.0                42             0.667                7
57315               1.000000           0.018013     0.039551          2              1               0                   0               0.0                42             0.667                7
31955               1.000000           0.018013     0.039482          2              1               0                   0               0.0                41             0.661                7
197956              0.400000           0.000000     0.028501          2              2               0                   0               0.0                12             0.343               10
126246              0.400000           0.000000     0.028347          2              2               0                   0               0.0                13             0.361               10
128125              0.727273           0.001363     0.052589          2              1               0                   0               0.0                53             0.716                1
161155              0.727273           0.001363     0.052087          2              1               0                   0               0.0                54             0.720                1
18133               0.241379           0.000331     0.044863          4              3               0                   0               0.0                62             0.697               11
216082              0.241379           0.000331     0.044836          4              3               0                   0               0.0                63             0.700               11
219064              0.295455           0.000331     0.038161          4              3               0                   0               0.0                37             0.649                5
194438              0.295455           0.000331     0.038161          4              3               0                   0               0.0                37             0.661                5
91011               0.236364           0.000331     0.043238          4              3               0                   0               0.0                60             0.698               10
20453               0.236364           0.000331     0.043233          4              3               0                   0               0.0                61             0.701               10
222957              0.366667           0.522907     0.034250          3              3               0                   0               0.0                19             0.413               12
224102              0.366667           0.522907     0.034250          3              3               0                   0               0.0                19             0.404               12

        DegitRatioInURL  NoOfEqualsInURL  NoOfQMarkInURL  NoOfAmpersandInURL  NoOfOtherSpecialCharsInURL  SpacialCharRatioInURL  IsHTTPS  LineOfCode  LargestLineLength  HasTitle  \
219489            0.054                0               0                   0                           5                  0.135        0           6              84248         0
57609             0.056                0               0                   0                           4                  0.111        0           6              84248         0
227564            0.524                0               0                   0                           3                  0.143        0         718              36376         1
27166             0.500                0               0                   0                           4                  0.182        0         716              33721         1
147448            0.113                0               0                   0                           7                  0.113        0          73               7884         1
189978            0.111                0               0                   0                           7                  0.111        0          73               7884         1
57315             0.111                0               0                   0                           7                  0.111        0          73               7884         1
31955             0.113                0               0                   0                           7                  0.113        0          73               7884         1
197956            0.286                0               0                   0                           6                  0.171        0         108                240         1
126246            0.278                0               0                   0                           6                  0.167        0         108                240         1
128125            0.014                0               0                   0                          13                  0.176        0         162               2158         1
161155            0.013                0               0                   0                          13                  0.173        0         162               2158         1
18133             0.124                0               0                   0                           9                  0.101        0           2               1091         1
216082            0.122                0               0                   0                           9                  0.100        0           2               1091         1
219064            0.088                0               0                   0                           8                  0.140        0         152               1878         1
194438            0.089                0               0                   0                           7                  0.125        0         152               1878         1
91011             0.116                0               0                   0                           9                  0.105        0           2               1091         1
20453             0.115                0               0                   0                           9                  0.103        0           2               1091         1
222957            0.261                0               0                   0                           8                  0.174        0         173                121         0
224102            0.255                0               0                   0                           9                  0.191        0         173                121         0

                                                    Title  DomainTitleMatchScore  URLTitleMatchScore  HasFavicon  Robots  IsResponsive  NoOfURLRedirect  NoOfSelfRedirect  HasDescription  NoOfPopup  \
219489                                                  0                    0.0                 0.0           0       0             0                0                 0               0          0
57609                                                   0                    0.0                 0.0           0       0             0                0                 0               0          0
227564                                           34149138                    0.0                 0.0           0       0             1                0                 0               1          0
27166                                            34149138                    0.0                 0.0           0       0             1                0                 0               1          0
147448   595221selcdnqwerty-ohdhdjejnnad-najahhyindex4htm                    0.0                 0.0           0       0             1                0                 0               1          0
189978  595221selcdnqwerty-ohdhdjejnnad-najahhyindex4html                    0.0                 0.0           0       0             1                0                 0               1          0
57315   595221selcdnqwerty-ohdhdjejnnad-najahhyindex8html                    0.0                 0.0           0       0             1                0                 0               1          0
31955    595221selcdnqwerty-ohdhdjejnnad-najahhyindex8htm                    0.0                 0.0           0       0             1                0                 0               1          0
197956                               91239125postchssmsph                    0.0                 0.0           0       1             1                0                 0               1          0
126246                              91239125postchssmsphp                    0.0                 0.0           0       1             1                0                 0               1          0
128125  akarealcomwp-adminjshkusanetfluincachun-gaccou...                    0.0                 0.0           0       0             1                0                 0               0          0
161155  akarealcomwp-adminjshkusanetfluincachun-gaccou...                    0.0                 0.0           0       0             1                0                 0               0          0
18133   app-batasotak1244acceskvoiffugw9-yk26ed5vg379p...                    0.0                 0.0           0       0             0                0                 0               0          0
216082  app-batasotak1244acceskvoiffugw9-yk26ed5vg379p...                    0.0                 0.0           0       0             0                0                 0               0          0
219064          app-inf0tacbxjsspw-ypj68pkov3l2ptemp-site                    0.0                 0.0           0       0             1                0                 0               0          0
194438          app-inf0tacbxjsspw-ypj68pkov3l2ptemp-site                    0.0                 0.0           0       0             1                0                 0               0          0
91011   app-mumerlah589iekskvoiffugw9-yk26ed5vg379ptem...                    0.0                 0.0           0       0             0                0                 0               0          0
20453   app-mumerlah589iekskvoiffugw9-yk26ed5vg379ptem...                    0.0                 0.0           0       0             0                0                 0               0          0
222957                                                  0                    0.0                 0.0           0       0             1                0                 0               0          0
224102                                                  0                    0.0                 0.0           0       0             1                0                 0               0          0

        NoOfiFrame  HasExternalFormSubmit  HasSocialNet  HasSubmitButton  HasHiddenFields  HasPasswordField  Bank  Pay  Crypto  HasCopyrightInfo  NoOfImage  NoOfCSS  NoOfJS  NoOfSelfRef  \
219489           0                      0             0                0                0                 0     0    1       0                 0          0        0       0            0
57609            0                      0             0                0                0                 0     0    1       0                 0          0        0       0            0
227564           0                      0             0                0                1                 0     0    0       1                 0          4        1       5           48
27166            0                      0             0                0                1                 0     0    0       1                 0          4        1       4           48
147448           0                      0             0                1                1                 1     0    0       0                 1          2        2       7            0
189978           0                      0             0                1                1                 1     0    0       0                 1          2        2       7            0
57315            0                      0             0                1                1                 1     0    0       0                 1          2        2       7            0
31955            0                      0             0                1                1                 1     0    0       0                 1          2        2       7            0
197956           0                      0             0                1                0                 0     0    0       0                 1          1        1       1            0
126246           0                      0             0                1                0                 0     0    0       0                 1          1        1       1            0
128125           0                      0             0                1                1                 0     0    0       0                 0          0        1       2            0
161155           0                      0             0                1                1                 0     0    0       0                 0          0        1       2            0
18133            0                      0             0                0                0                 0     0    0       0                 0          0        0       0            0
216082           0                      0             0                0                0                 0     0    0       0                 0          0        0       0            0
219064           0                      0             0                1                0                 1     0    1       0                 0          3        4       0            0
194438           0                      0             0                1                0                 1     0    1       0                 0          3        4       0            0
91011            0                      0             0                0                0                 0     0    0       0                 0          0        0       0            0
20453            0                      0             0                0                0                 0     0    0       0                 0          0        0       0            0
222957           0                      0             0                1                0                 1     1    1       0                 0          3        1       2            0
224102           0                      0             0                1                0                 1     1    1       0                 0          3        1       2            0

        NoOfEmptyRef  NoOfExternalRef  label
219489             0                0      0

In [56]:
columns_to_check = [
    'URL',
    'URLLength',
    'URLSimilarityIndex',
    'URLCharProb',
    'NoOfLettersInURL',
    'LetterRatioInURL',
    'NoOfDegitsInURL',
    'DegitRatioInURL',
    'NoOfEqualsInURL',
    'NoOfQMarkInURL',
    'NoOfAmpersandInURL',
    'NoOfOtherSpecialCharsInURL',
    'SpacialCharRatioInURL',
    'URLTitleMatchScore',
    'NoOfURLRedirect'
]

print("✓ Checking for feature values associated with conflicting labels.")

for col in columns_to_check:
    label_counts = df.groupby(col)["label"].nunique()
    conflicting = label_counts[label_counts > 1]

    print(f"\nColumn: {col}")
    print(f"Conflicting values: {len(conflicting)}")
    print(conflicting.head(10))

✓ Checking for feature values associated with conflicting labels.

Column: URL
Conflicting values: 0
Series([], Name: label, dtype: int64)

Column: URLLength
Conflicting values: 41
URLLength
15    2
16    2
17    2
18    2
19    2
20    2
21    2
22    2
23    2
24    2
Name: label, dtype: int64

Column: URLSimilarityIndex
Conflicting values: 1
URLSimilarityIndex
100.0    2
Name: label, dtype: int64

Column: URLCharProb
Conflicting values: 650
URLCharProb
0.022652    2
0.028524    2
0.030240    2
0.031564    2
0.032249    2
0.033601    2
0.037676    2
0.039907    2
0.040439    2
0.041228    2
Name: label, dtype: int64

Column: NoOfLettersInURL
Conflicting values: 40
NoOfLettersInURL
1     2
2     2
3     2
4     2
5     2
6     2
7     2
8     2
9     2
10    2
Name: label, dtype: int64

Column: LetterRatioInURL
Conflicting values: 192
LetterRatioInURL
0.056    2
0.059    2
0.062    2
0.067    2
0.083    2
0.087    2
0.091    2
0.095    2
0.100    2
0.105    2
Name: label, dtype: int64

Column: NoOfDegitsInURL
Conflicting values: 9
NoOfDegitsInURL
0    2
1    2
2    2
3    2
4    2
5    2
6    2
7    2
8    2
Name: label, dtype: int64

Column: DegitRatioInURL
Conflicting values: 94
DegitRatioInURL
0.000    2
0.023    2
0.024    2
0.025    2
0.026    2
0.027    2
0.028    2
0.029    2
0.030    2
0.031    2
Name: label, dtype: int64

Column: NoOfEqualsInURL
Conflicting values: 1
NoOfEqualsInURL
0    2
Name: label, dtype: int64

Column: NoOfQMarkInURL
Conflicting values: 1
NoOfQMarkInURL
0    2
Name: label, dtype: int64

Column: NoOfAmpersandInURL
Conflicting values: 1
NoOfAmpersandInURL
0    2
Name: label, dtype: int64

Column: NoOfOtherSpecialCharsInURL
Conflicting values: 7
NoOfOtherSpecialCharsInURL
1    2
2    2
3    2
4    2
5    2
6    2
7    2
Name: label, dtype: int64

Column: SpacialCharRatioInURL
Conflicting values: 108
SpacialCharRatioInURL
0.018    2
0.020    2
0.021    2
0.022    2
0.023    2
0.024    2
0.025    2
0.026    2
0.027    2
0.028    2
Name: label, dtype: int64

Column: URLTitleMatchScore
Conflicting values: 46
URLTitleMatchScore
0.000000     2
10.000000    2
25.000000    2
33.333333    2
37.500000    2
50.000000    2
60.000000    2
62.500000    2
66.666667    2
69.230769    2
Name: label, dtype: int64

Column: NoOfURLRedirect
Conflicting values: 2
NoOfURLRedirect
0    2
1    2
Name: label, dtype: int64

In [73]:
print("✓ Removing duplicate URL entries.")

original_rows = len(df)

clean_df = df.drop_duplicates(
    subset=["URL"],
    keep="first"
).copy()

removed_rows = original_rows - len(clean_df)

print("Original rows:", original_rows)
print("Cleaned rows:", len(clean_df))
print("Rows removed:", removed_rows)
print("Duplicate URLs remaining:", clean_df["URL"].duplicated().sum())

print("\n✓ Duplicate URL removal completed.")

✓ Removing duplicate URL entries.
Original rows: 235795
Cleaned rows: 235370
Rows removed: 425
Duplicate URLs remaining: 0

✓ Duplicate URL removal completed.

In [57]:
missing = df.isnull().sum()

missing_table = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": (missing / len(df) * 100).round(4)
})

missing_table = missing_table[
    missing_table["Missing_Count"] > 0
].sort_values("Missing_Count", ascending=False)

print("✓ Missing value analysis completed.")

if missing_table.empty:
    print("No missing values found in the dataset.")
else:
    display(missing_table)

print("\nTotal missing values:", df.isnull().sum().sum())

✓ Missing value analysis completed.
No missing values found in the dataset.

Total missing values: 0

In [58]:
numeric_cols = df.select_dtypes(include=np.number).columns

inf_counts = np.isinf(df[numeric_cols]).sum()

inf_table = inf_counts[inf_counts > 0]

print("✓ Infinite value check completed.")

if inf_table.empty:
    print("No infinite values found in numeric features.")
else:
    print("Columns containing infinity:")
    print(inf_table)

✓ Infinite value check completed.
No infinite values found in numeric features.

In [59]:
print("✓ Target label distribution analysis completed.\n")

print("Label counts:")
print(df["label"].value_counts(dropna=False))

print("\nLabel percentages:")
print(
    df["label"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

print("\nUnique labels:")
print(df["label"].unique())

✓ Target label distribution analysis completed.

Label counts:
label
1    134850
0    100945
Name: count, dtype: int64

Label percentages:
label
1    57.19
0    42.81
Name: proportion, dtype: float64

Unique labels:
[1 0]

In [60]:
print("✓ URL value validation completed.\n")

print("URL data type:", df["URL"].dtype)
print("Missing URLs:", df["URL"].isna().sum())
print(
    "Empty URLs:",
    (df["URL"].astype(str).str.strip() == "").sum()
)

print("\nRaw URL string length statistics:")
print(df["URL"].astype(str).str.len().describe())

✓ URL value validation completed.

URL data type: object
Missing URLs: 0
Empty URLs: 0

Raw URL string length statistics:
count    235795.000000
mean         35.366954
std          41.214346
min          14.000000
25%          24.000000
50%          28.000000
75%          35.000000
max        6097.000000
Name: URL, dtype: float64

In [61]:
url_series = df["URL"].astype(str).str.strip()

invalid_url_mask = (
    (url_series == "") |
    (url_series.str.lower() == "nan") |
    (url_series.str.lower() == "none")
)

print("✓ Invalid URL string check completed.")
print("Potentially invalid URL strings:", invalid_url_mask.sum())

print("\nExamples of potentially invalid URLs:")
df.loc[invalid_url_mask, ["URL", "label"]].head(20)

✓ Invalid URL string check completed.
Potentially invalid URL strings: 0

Examples of potentially invalid URLs:

Empty DataFrame
Columns: [URL, label]
Index: []

In [62]:
dtype_table = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Values": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ]
})

print("✓ Column data type and cardinality summary generated.")
dtype_table

✓ Column data type and cardinality summary generated.

                        Column Data_Type  Unique_Values
0                     FILENAME    object         235795
1                          URL    object         235370
2                    URLLength     int64            482
3                       Domain    object         220086
4                 DomainLength     int64            101
5                   IsDomainIP     int64              2
6                          TLD    object            695
7           URLSimilarityIndex   float64          36360
8         CharContinuationRate   float64            898
9            TLDLegitimateProb   float64            465
10                 URLCharProb   float64         227421
11                   TLDLength     int64             12
12               NoOfSubDomain     int64             10
13              HasObfuscation     int64              2
14          NoOfObfuscatedChar     int64             20
15            ObfuscationRatio   float64            146
16            NoOfLettersInURL     int64            421
17            LetterRatioInURL   float64            709
18             NoOfDegitsInURL     int64            182
19             DegitRatioInURL   float64            575
20             NoOfEqualsInURL     int64             25
21              NoOfQMarkInURL     int64              5
22          NoOfAmpersandInURL     int64             31
23  NoOfOtherSpecialCharsInURL     int64             74
24       SpacialCharRatioInURL   float64            240
25                     IsHTTPS     int64              2
26                  LineOfCode     int64          10738
27           LargestLineLength     int64          26181
28                    HasTitle     int64              2
29                       Title    object         197874
30       DomainTitleMatchScore   float64            152
31          URLTitleMatchScore   float64            497
32                  HasFavicon     int64              2
33                      Robots     int64              2
34                IsResponsive     int64              2
35             NoOfURLRedirect     int64              2
36            NoOfSelfRedirect     int64              2
37              HasDescription     int64              2
38                   NoOfPopup     int64            115
39                  NoOfiFrame     int64            119
40       HasExternalFormSubmit     int64              2
41                HasSocialNet     int64              2
42             HasSubmitButton     int64              2
43             HasHiddenFields     int64              2
44            HasPasswordField     int64              2
45                        Bank     int64              2
46                         Pay     int64              2
47                      Crypto     int64              2
48            HasCopyrightInfo     int64              2
49                   NoOfImage     int64            992
50                     NoOfCSS     int64            209
51                      NoOfJS     int64            253
52                 NoOfSelfRef     int64           1374
53                NoOfEmptyRef     int64            296
54             NoOfExternalRef     int64           1191
55                       label     int64              2

In [63]:
constant_cols = [
    col for col in df.columns
    if df[col].nunique(dropna=False) <= 1
]

print("\n✓ Constant column check completed.")
print("Constant columns:")
print(constant_cols)

✓ Constant column check completed.
Constant columns:
[]

In [64]:
cardinality = pd.DataFrame({
    "Column": df.columns,
    "Unique_Count": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ],
    "Unique_Ratio": [
        df[col].nunique(dropna=False) / len(df)
        for col in df.columns
    ]
})

print("✓ Feature cardinality analysis completed.")
print("\nColumns sorted by unique-value ratio:")

display(
    cardinality.sort_values(
        "Unique_Ratio",
        ascending=False
    )
)

✓ Feature cardinality analysis completed.

Columns sorted by unique-value ratio:

                        Column  Unique_Count  Unique_Ratio
0                     FILENAME        235795      1.000000
1                          URL        235370      0.998198
10                 URLCharProb        227421      0.964486
3                       Domain        220086      0.933379
29                       Title        197874      0.839178
7           URLSimilarityIndex         36360      0.154202
27           LargestLineLength         26181      0.111033
26                  LineOfCode         10738      0.045540
52                 NoOfSelfRef          1374      0.005827
54             NoOfExternalRef          1191      0.005051
49                   NoOfImage           992      0.004207
8         CharContinuationRate           898      0.003808
17            LetterRatioInURL           709      0.003007
6                          TLD           695      0.002947
19             DegitRatioInURL           575      0.002439
31          URLTitleMatchScore           497      0.002108
2                    URLLength           482      0.002044
9            TLDLegitimateProb           465      0.001972
16            NoOfLettersInURL           421      0.001785
53                NoOfEmptyRef           296      0.001255
51                      NoOfJS           253      0.001073
24       SpacialCharRatioInURL           240      0.001018
50                     NoOfCSS           209      0.000886
18             NoOfDegitsInURL           182      0.000772
30       DomainTitleMatchScore           152      0.000645
15            ObfuscationRatio           146      0.000619
39                  NoOfiFrame           119      0.000505
38                   NoOfPopup           115      0.000488
4                 DomainLength           101      0.000428
23  NoOfOtherSpecialCharsInURL            74      0.000314
22          NoOfAmpersandInURL            31      0.000131
20             NoOfEqualsInURL            25      0.000106
14          NoOfObfuscatedChar            20      0.000085
11                   TLDLength            12      0.000051
12               NoOfSubDomain            10      0.000042
21              NoOfQMarkInURL             5      0.000021
47                      Crypto             2      0.000008
46                         Pay             2      0.000008
48            HasCopyrightInfo             2      0.000008
43             HasHiddenFields             2      0.000008
45                        Bank             2      0.000008
44            HasPasswordField             2      0.000008
28                    HasTitle             2      0.000008
42             HasSubmitButton             2      0.000008
41                HasSocialNet             2      0.000008
40       HasExternalFormSubmit             2      0.000008
37              HasDescription             2      0.000008
36            NoOfSelfRedirect             2      0.000008
35             NoOfURLRedirect             2      0.000008
34                IsResponsive             2      0.000008
33                      Robots             2      0.000008
32                  HasFavicon             2      0.000008
25                     IsHTTPS             2      0.000008
13              HasObfuscation             2      0.000008
5                   IsDomainIP             2      0.000008
55                       label             2      0.000008

In [65]:
potential_id_cols = [
    col for col in df.columns
    if any(
        word in col.lower()
        for word in ["id", "index", "unnamed"]
    )
]

print("✓ Potential identifier/index column check completed.")
print("Potential ID or index columns:")
print(potential_id_cols)

✓ Potential identifier/index column check completed.
Potential ID or index columns:
['URLSimilarityIndex', 'HasHiddenFields']

In [66]:
numeric_summary = df.select_dtypes(include=np.number).describe().T

print("✓ Numeric feature range and distribution analysis completed.")

numeric_summary[
    ["min", "max", "mean", "std"]
].sort_values("max", ascending=False)

✓ Numeric feature range and distribution analysis completed.

                                  min           max          mean            std
LargestLineLength           22.000000  1.397573e+07  12789.532624  152201.099228
LineOfCode                   2.000000  4.426660e+05   1141.900443    3419.950513
NoOfCSS                      0.000000  3.582000e+04      6.333111      74.866296
NoOfExternalRef              0.000000  2.751600e+04     49.262516     161.027430
NoOfSelfRef                  0.000000  2.739700e+04     65.071113     176.687539
NoOfImage                    0.000000  8.956000e+03     26.075689      79.411815
NoOfJS                       0.000000  6.957000e+03     10.522305      22.312192
URLLength                   13.000000  6.097000e+03     34.573095      41.314153
NoOfLettersInURL             0.000000  5.191000e+03     19.428919      29.090330
NoOfEmptyRef                 0.000000  4.887000e+03      2.377629      17.641097
NoOfDegitsInURL              0.000000  2.011000e+03      1.881011      11.886695
NoOfiFrame                   0.000000  1.602000e+03      1.588638       5.762561
NoOfPopup                    0.000000  6.020000e+02      0.221765       3.870540
NoOfOtherSpecialCharsInURL   0.000000  4.990000e+02      2.340198       3.527603
NoOfObfuscatedChar           0.000000  4.470000e+02      0.024861       1.876249
NoOfEqualsInURL              0.000000  1.760000e+02      0.062241       0.934704
NoOfAmpersandInURL           0.000000  1.490000e+02      0.025056       0.836448
DomainLength                 4.000000  1.100000e+02     21.470396       9.150793
URLTitleMatchScore           0.000000  1.000000e+02     52.122098      49.600564
DomainTitleMatchScore        0.000000  1.000000e+02     50.131427      49.676981
URLSimilarityIndex           0.155574  1.000000e+02     78.430778      28.976055
TLDLength                    2.000000  1.300000e+01      2.764456       0.599739
NoOfSubDomain                0.000000  1.000000e+01      1.164758       0.600969
NoOfQMarkInURL               0.000000  4.000000e+00      0.029403       0.193505
HasExternalFormSubmit        0.000000  1.000000e+00      0.043987       0.205067
HasSocialNet                 0.000000  1.000000e+00      0.456570       0.498111
IsDomainIP                   0.000000  1.000000e+00      0.002706       0.051946
CharContinuationRate         0.000000  1.000000e+00      0.845508       0.216632
HasCopyrightInfo             0.000000  1.000000e+00      0.486775       0.499826
Crypto                       0.000000  1.000000e+00      0.023474       0.151403
Pay                          0.000000  1.000000e+00      0.237007       0.425247
Bank                         0.000000  1.000000e+00      0.127089       0.333074
HasPasswordField             0.000000  1.000000e+00      0.102263       0.302994
HasHiddenFields              0.000000  1.000000e+00      0.377799       0.484838
HasSubmitButton              0.000000  1.000000e+00      0.414301       0.492602
label                        0.000000  1.000000e+00      0.571895       0.494805
IsHTTPS                      0.000000  1.000000e+00      0.782625       0.412461
HasObfuscation               0.000000  1.000000e+00      0.002057       0.045306
HasDescription               0.000000  1.000000e+00      0.440183       0.496410
NoOfSelfRedirect             0.000000  1.000000e+00      0.040107       0.196210
NoOfURLRedirect              0.000000  1.000000e+00      0.133438       0.340048
IsResponsive                 0.000000  1.000000e+00      0.624513       0.484249
Robots                       0.000000  1.000000e+00      0.266541       0.442151
HasFavicon                   0.000000  1.000000e+00      0.361768       0.480513
HasTitle                     0.000000  1.000000e+00      0.861261       0.345675
LetterRatioInURL             0.000000  9.260000e-01      0.515946       0.123315
DegitRatioInURL              0.000000  6.840000e-01      0.028616       0.070897
TLDLegitimateProb            0.000000  5.229071e-01      0.260423       0.251628
SpacialCharRatioInURL        0.000000  3.970000e-01      0.063309       0.032393
ObfuscationRatio             0.000000  3.480000e-01      0.000138       0.003817
URLCharProb                  0.001083  9.082366e-02      0.055747       0.010587

In [67]:
correlations = (
    df.select_dtypes(include=np.number)
      .corr()["label"]
      .sort_values(ascending=False)
)

print("✓ Correlation analysis with the target label completed.")
correlations

✓ Correlation analysis with the target label completed.

label                         1.000000
URLSimilarityIndex            0.860358
HasSocialNet                  0.784255
HasCopyrightInfo              0.743358
HasDescription                0.690232
IsHTTPS                       0.609132
DomainTitleMatchScore         0.584905
HasSubmitButton               0.578561
IsResponsive                  0.548608
URLTitleMatchScore            0.539419
HasHiddenFields               0.507731
HasFavicon                    0.493711
URLCharProb                   0.469749
CharContinuationRate          0.467735
HasTitle                      0.459725
Robots                        0.392620
NoOfJS                        0.373500
Pay                           0.359747
NoOfSelfRef                   0.316211
NoOfImage                     0.274658
LineOfCode                    0.272257
NoOfExternalRef               0.258627
NoOfiFrame                    0.225822
Bank                          0.188959
HasExternalFormSubmit         0.167574
HasPasswordField              0.138183
NoOfEmptyRef                  0.109235
Crypto                        0.099610
TLDLegitimateProb             0.097389
NoOfCSS                       0.068109
NoOfPopup                     0.047391
NoOfSubDomain                -0.005955
NoOfObfuscatedChar           -0.015315
NoOfAmpersandInURL           -0.034622
LargestLineLength            -0.041111
ObfuscationRatio             -0.041915
NoOfURLRedirect              -0.046456
HasObfuscation               -0.052473
IsDomainIP                   -0.060202
NoOfSelfRedirect             -0.076463
NoOfEqualsInURL              -0.076963
TLDLength                    -0.079159
NoOfQMarkInURL               -0.175621
NoOfDegitsInURL              -0.177980
URLLength                    -0.233445
NoOfLettersInURL             -0.258090
DomainLength                 -0.283152
NoOfOtherSpecialCharsInURL   -0.358891
LetterRatioInURL             -0.367794
DegitRatioInURL              -0.432032
SpacialCharRatioInURL        -0.533537
Name: label, dtype: float64

In [68]:
feature_report = pd.DataFrame({
    "Feature": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Unique_Count": [
        df[col].nunique(dropna=False)
        for col in df.columns
    ],
    "Missing_Count": [
        df[col].isna().sum()
        for col in df.columns
    ]
})

print("✓ Feature quality report generated.")
feature_report

✓ Feature quality report generated.

                       Feature Data_Type  Unique_Count  Missing_Count
0                     FILENAME    object        235795              0
1                          URL    object        235370              0
2                    URLLength     int64           482              0
3                       Domain    object        220086              0
4                 DomainLength     int64           101              0
5                   IsDomainIP     int64             2              0
6                          TLD    object           695              0
7           URLSimilarityIndex   float64         36360              0
8         CharContinuationRate   float64           898              0
9            TLDLegitimateProb   float64           465              0
10                 URLCharProb   float64        227421              0
11                   TLDLength     int64            12              0
12               NoOfSubDomain     int64            10              0
13              HasObfuscation     int64             2              0
14          NoOfObfuscatedChar     int64            20              0
15            ObfuscationRatio   float64           146              0
16            NoOfLettersInURL     int64           421              0
17            LetterRatioInURL   float64           709              0
18             NoOfDegitsInURL     int64           182              0
19             DegitRatioInURL   float64           575              0
20             NoOfEqualsInURL     int64            25              0
21              NoOfQMarkInURL     int64             5              0
22          NoOfAmpersandInURL     int64            31              0
23  NoOfOtherSpecialCharsInURL     int64            74              0
24       SpacialCharRatioInURL   float64           240              0
25                     IsHTTPS     int64             2              0
26                  LineOfCode     int64         10738              0
27           LargestLineLength     int64         26181              0
28                    HasTitle     int64             2              0
29                       Title    object        197874              0
30       DomainTitleMatchScore   float64           152              0
31          URLTitleMatchScore   float64           497              0
32                  HasFavicon     int64             2              0
33                      Robots     int64             2              0
34                IsResponsive     int64             2              0
35             NoOfURLRedirect     int64             2              0
36            NoOfSelfRedirect     int64             2              0
37              HasDescription     int64             2              0
38                   NoOfPopup     int64           115              0
39                  NoOfiFrame     int64           119              0
40       HasExternalFormSubmit     int64             2              0
41                HasSocialNet     int64             2              0
42             HasSubmitButton     int64             2              0
43             HasHiddenFields     int64             2              0
44            HasPasswordField     int64             2              0
45                        Bank     int64             2              0
46                         Pay     int64             2              0
47                      Crypto     int64             2              0
48            HasCopyrightInfo     int64             2              0
49                   NoOfImage     int64           992              0
50                     NoOfCSS     int64           209              0
51                      NoOfJS     int64           253              0
52                 NoOfSelfRef     int64          1374              0
53                NoOfEmptyRef     int64           296              0
54             NoOfExternalRef     int64          1191              0
55                       label     int64             2              0

In [69]:
candidate_url_features = [
    "URLLength",
    "DomainLength",
    "IsDomainIP",
    "TLDLength",
    "NoOfSubDomain",
    "HasObfuscation",
    "NoOfObfuscatedChar",
    "ObfuscationRatio",
    "NoOfLettersInURL",
    "LetterRatioInURL",
    "NoOfDegitsInURL",
    "DegitRatioInURL",
    "NoOfEqualsInURL",
    "NoOfQMarkInURL",
    "NoOfAmpersandInURL",
    "NoOfOtherSpecialCharsInURL",
    "SpacialCharRatioInURL",
    "IsHTTPS"
]

print("✓ Candidate URL feature list defined.")

missing_candidates = [
    col for col in candidate_url_features
    if col not in df.columns
]

print("\nMissing candidate features:")
print(missing_candidates)

print("\nCandidate URL feature statistics:")
df[candidate_url_features + ["label"]].describe().T

✓ Candidate URL feature list defined.

Missing candidate features:
[]

Candidate URL feature statistics:

                               count       mean        std   min     25%     50%     75%       max
URLLength                   235795.0  34.573095  41.314153  13.0  23.000  27.000  34.000  6097.000
DomainLength                235795.0  21.470396   9.150793   4.0  16.000  20.000  24.000   110.000
IsDomainIP                  235795.0   0.002706   0.051946   0.0   0.000   0.000   0.000     1.000
TLDLength                   235795.0   2.764456   0.599739   2.0   2.000   3.000   3.000    13.000
NoOfSubDomain               235795.0   1.164758   0.600969   0.0   1.000   1.000   1.000    10.000
HasObfuscation              235795.0   0.002057   0.045306   0.0   0.000   0.000   0.000     1.000
NoOfObfuscatedChar          235795.0   0.024861   1.876249   0.0   0.000   0.000   0.000   447.000
ObfuscationRatio            235795.0   0.000138   0.003817   0.0   0.000   0.000   0.000     0.348
NoOfLettersInURL            235795.0  19.428919  29.090330   0.0  10.000  14.000  20.000  5191.000
LetterRatioInURL            235795.0   0.515946   0.123315   0.0   0.435   0.519   0.594     0.926
NoOfDegitsInURL             235795.0   1.881011  11.886695   0.0   0.000   0.000   0.000  2011.000
DegitRatioInURL             235795.0   0.028616   0.070897   0.0   0.000   0.000   0.000     0.684
NoOfEqualsInURL             235795.0   0.062241   0.934704   0.0   0.000   0.000   0.000   176.000
NoOfQMarkInURL              235795.0   0.029403   0.193505   0.0   0.000   0.000   0.000     4.000
NoOfAmpersandInURL          235795.0   0.025056   0.836448   0.0   0.000   0.000   0.000   149.000
NoOfOtherSpecialCharsInURL  235795.0   2.340198   3.527603   0.0   1.000   1.000   3.000   499.000
SpacialCharRatioInURL       235795.0   0.063309   0.032393   0.0   0.038   0.050   0.083     0.397
IsHTTPS                     235795.0   0.782625   0.412461   0.0   1.000   1.000   1.000     1.000
label                       235795.0   0.571895   0.494805   0.0   0.000   1.000   1.000     1.000

In [70]:
# Check whether URLLength matches the actual URL string length

actual_url_length = df["URL"].astype(str).str.len()

url_length_mismatch = (
    actual_url_length != df["URLLength"]
)

print("✓ URL length consistency check completed.")
print("URLLength mismatches:", url_length_mismatch.sum())
print(
    "Mismatch percentage:",
    round(url_length_mismatch.mean() * 100, 4),
    "%"
)

print("\nExamples of URLLength mismatches:")
df.loc[
    url_length_mismatch,
    ["URL", "URLLength"]
].head(20)

✓ URL length consistency check completed.
URLLength mismatches: 187151
Mismatch percentage: 79.3702 %

Examples of URLLength mismatches:

                                   URL  URLLength
0     https://www.southbankmosaics.com         31
1             https://www.uni-mainz.de         23
2       https://www.voicefmradio.co.uk         29
3          https://www.sfnmjournal.com         26
4   https://www.rewildingargentina.org         33
5      https://www.globalreporting.org         30
6           https://www.saffronart.com         25
7           https://www.nerdscandy.com         25
8       https://www.hyderabadonline.in         29
9                  https://www.aap.org         18
10  https://www.religionenlibertad.com         33
11             http://www.teramill.com         22
12        https://www.socialpolicy.org         27
13               https://www.aoh61.com         20
14         https://www.bulgariaski.com         26
15           https://www.brightika.com         24
16               https://www.motley.ie         20
17              https://www.funzine.hu         21
18              https://www.dixxon.com         21
19             https://www.ooty.ind.in         22

In [43]:
actual_digit_count = (
    df["URL"]
    .astype(str)
    .str.count(r"\d")
)

digit_mismatch = (
    actual_digit_count != df["NoOfDegitsInURL"]
)

print("Digit-count mismatches:", digit_mismatch.sum())
print(
    "Mismatch percentage:",
    round(digit_mismatch.mean() * 100, 4),
    "%"
)
actual_equals_count = (
    df["URL"]
    .astype(str)
    .str.count("=")
)

equals_mismatch = (
    actual_equals_count != df["NoOfEqualsInURL"]
)

print("Equals-count mismatches:", equals_mismatch.sum())
actual_qmark_count = (
    df["URL"]
    .astype(str)
    .str.count(r"\?")
)

qmark_mismatch = (
    actual_qmark_count != df["NoOfQMarkInURL"]
)

print("Question-mark mismatches:", qmark_mismatch.sum())
actual_ampersand_count = (
    df["URL"]
    .astype(str)
    .str.count("&")
)

ampersand_mismatch = (
    actual_ampersand_count != df["NoOfAmpersandInURL"]
)

print("Ampersand mismatches:", ampersand_mismatch.sum())

Digit-count mismatches: 1210
Mismatch percentage: 0.5132 %
Equals-count mismatches: 249
Question-mark mismatches: 12
Ampersand mismatches: 3172

In [44]:
duplicate_urls = df[df["URL"].duplicated(keep=False)].copy()

print("Rows involved in duplicate URLs:", len(duplicate_urls))
print("Unique duplicated URLs:", duplicate_urls["URL"].nunique())

duplicate_urls[["URL", "label"]].sort_values("URL").head(30)
duplicate_label_check = (
    duplicate_urls
    .groupby("URL")["label"]
    .nunique()
)

conflicting_duplicate_urls = duplicate_label_check[
    duplicate_label_check > 1
]

print(
    "Duplicate URLs with conflicting labels:",
    len(conflicting_duplicate_urls)
)

Rows involved in duplicate URLs: 850
Unique duplicated URLs: 425
Duplicate URLs with conflicting labels: 0

In [45]:
# ============================================================
# FINAL URL DATA CLEANING
# ============================================================

clean_df = df.copy()

print("Original shape:", clean_df.shape)

# ------------------------------------------------------------
# 1. Remove identifier column
# ------------------------------------------------------------

if "FILENAME" in clean_df.columns:
    clean_df = clean_df.drop(columns=["FILENAME"])
    print("Removed: FILENAME")

# ------------------------------------------------------------
# 2. Remove exact duplicate rows
# ------------------------------------------------------------

before = len(clean_df)

clean_df = clean_df.drop_duplicates()

after = len(clean_df)

print("Exact duplicate rows removed:", before - after)

# ------------------------------------------------------------
# 3. Check duplicate URLs
# ------------------------------------------------------------

duplicate_url_count = clean_df["URL"].duplicated().sum()

print("Duplicate URL occurrences:", duplicate_url_count)

# Since duplicate URLs have already been verified
# to have no conflicting labels, keep one occurrence.
clean_df = clean_df.drop_duplicates(subset=["URL"], keep="first")

print("Duplicate URLs removed:", duplicate_url_count)

# ------------------------------------------------------------
# 4. Remove rows with missing values
# ------------------------------------------------------------

missing_before = clean_df.isna().sum().sum()

clean_df = clean_df.dropna()

print("Missing values before removal:", missing_before)
print("Rows after missing-value removal:", len(clean_df))

# ------------------------------------------------------------
# 5. Remove infinite numeric values
# ------------------------------------------------------------

numeric_columns = clean_df.select_dtypes(include=np.number).columns

infinite_mask = np.isinf(clean_df[numeric_columns]).any(axis=1)

print("Rows containing infinite values:", infinite_mask.sum())

clean_df = clean_df.loc[~infinite_mask].copy()

# ------------------------------------------------------------
# 6. Validate labels
# ------------------------------------------------------------

print("\nLabel values:")
print(clean_df["label"].value_counts())

invalid_labels = ~clean_df["label"].isin([0, 1])

print("Invalid label rows:", invalid_labels.sum())

clean_df = clean_df.loc[~invalid_labels].copy()

# ------------------------------------------------------------
# 7. Final validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL CLEANED DATASET")
print("=" * 70)

print("Final shape:", clean_df.shape)
print("Missing values:", clean_df.isna().sum().sum())
print("Duplicate rows:", clean_df.duplicated().sum())
print("Duplicate URLs:", clean_df["URL"].duplicated().sum())
print("Infinite values:", np.isinf(
    clean_df.select_dtypes(include=np.number)
).sum().sum())

print("\nLabel distribution:")
print(clean_df["label"].value_counts())

# ------------------------------------------------------------
# 8. Save cleaned dataset
# ------------------------------------------------------------

OUTPUT_PATH = PROCESSED_DIR / "url_cleaned.csv"

clean_df.to_csv(OUTPUT_PATH, index=False)

print("\nSaved cleaned dataset to:")
print(OUTPUT_PATH)

Original shape: (235795, 56)
Removed: FILENAME
Exact duplicate rows removed: 0
Duplicate URL occurrences: 425
Duplicate URLs removed: 425
Missing values before removal: 0
Rows after missing-value removal: 235370
Rows containing infinite values: 0

Label values:
label
1    134850
0    100520
Name: count, dtype: int64
Invalid label rows: 0

======================================================================
FINAL CLEANED DATASET
======================================================================
Final shape: (235370, 55)
Missing values: 0
Duplicate rows: 0
Duplicate URLs: 0
Infinite values: 0

Label distribution:
label
1    134850
0    100520
Name: count, dtype: int64

Saved cleaned dataset to:
C:\Users\BHUMIKA.G\Multimodal\data\processed\url_cleaned.csv

In [76]:
print("""# URL Dataset Cleaning — Summary

The UCI PhiUSIIL Phishing URL Dataset was analyzed and cleaned before being used for further model development.

### Dataset Summary

* Original dataset: **235,795 rows × 56 columns**
* `FILENAME` was identified as an identifier column and removed.
* No exact duplicate rows were found.
* **425 duplicate URL values** were identified and removed.
* Duplicate URLs had **no conflicting labels**.
* No missing values were found.
* No infinite values were found.
* No invalid label values were found.
* No obviously invalid or empty URL strings were found.

### Final Dataset

* Final size: **235,370 rows × 55 columns**
* Duplicate rows: **0**
* Duplicate URLs: **0**
* Missing values: **0**
* Infinite values: **0**
* Invalid labels: **0**

### Final Label Distribution

* **Phishing (1): 134,850**
* **Legitimate (0): 100,520**

### Important Findings

* Several features showed strong relationships with the target label, including `URLSimilarityIndex`, `HasSocialNet`, `HasCopyrightInfo`, `HasDescription`, and `IsHTTPS`.
* Several numerical features contained unusually large values. These were retained because large values alone do not establish that the records are erroneous.
* Some dataset-provided URL features did not exactly match values independently calculated from the URL string. The original dataset-provided values were therefore preserved rather than overwritten.

### Output

The cleaned dataset was saved as:

`data/processed/url_cleaned.csv`

**Cleaning completed successfully.**

###Note 
— Identifier Column:
An identifier column is a column used to uniquely identify or distinguish each record in a dataset. It generally does not contain meaningful information for predicting the target. In this dataset, FILENAME was treated as an identifier and removed.
 — Conflicting Labels:
A conflicting label occurs when the same input/value appears with different target labels in the dataset. For example, if the same URL is labelled both 0 (legitimate) and 1 (phishing), it has a conflicting label. In this dataset, duplicate URLs were checked and no conflicting labels were found.
""")

# URL Dataset Cleaning — Summary

The UCI PhiUSIIL Phishing URL Dataset was analyzed and cleaned before being used for further model development.

### Dataset Summary

* Original dataset: **235,795 rows × 56 columns**
* `FILENAME` was identified as an identifier column and removed.
* No exact duplicate rows were found.
* **425 duplicate URL values** were identified and removed.
* Duplicate URLs had **no conflicting labels**.
* No missing values were found.
* No infinite values were found.
* No invalid label values were found.
* No obviously invalid or empty URL strings were found.

### Final Dataset

* Final size: **235,370 rows × 55 columns**
* Duplicate rows: **0**
* Duplicate URLs: **0**
* Missing values: **0**
* Infinite values: **0**
* Invalid labels: **0**

### Final Label Distribution

* **Phishing (1): 134,850**
* **Legitimate (0): 100,520**

### Important Findings

* Several features showed strong relationships with the target label, including `URLSimilarityIndex`, `HasSocialNet`, `HasCopyrightInfo`, `HasDescription`, and `IsHTTPS`.
* Several numerical features contained unusually large values. These were retained because large values alone do not establish that the records are erroneous.
* Some dataset-provided URL features did not exactly match values independently calculated from the URL string. The original dataset-provided values were therefore preserved rather than overwritten.

### Output

The cleaned dataset was saved as:

`data/processed/url_cleaned.csv`

**Cleaning completed successfully.**

###Note
— Identifier Column:
An identifier column is a column used to uniquely identify or distinguish each record in a dataset. It generally does not contain meaningful information for predicting the target. In this dataset, FILENAME was treated as an identifier and removed.
 — Conflicting Labels:
A conflicting label occurs when the same input/value appears with different target labels in the dataset. For example, if the same URL is labelled both 0 (legitimate) and 1 (phishing), it has a conflicting label. In this dataset, duplicate URLs were checked and no conflicting labels were found.